---
# Variables defining Hashicorp Vault specific values used in defaults

_bbcrd_vault_binary: vault

_bbcrd_vault_systemd_unit: vault

_bbcrd_vault_user: vault
_bbcrd_vault_group: vault

_bbcrd_vault_config_dir: /etc/vault

_bbcrd_vault_data_dir: /var/lib/vault
